---
- name: Create Azure Bastion and related resources
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Create public IP for Bastion
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ bastion_vm_name }}-PIP"
        sku: Standard
        location: "{{ location }}"
        allocation_method: Static

    - name: Create Bastion host
      azure.azcollection.azure_rm_bastionhost:
        resource_group: "{{ resource_group }}"
        name: "{{ bastion_vm_name }}"
        location: "{{ location }}"
        sku:
          name: Standard
        ip_configurations:
          - name: BastionIPConfig
            subnet:
              id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ vnet_name }}/subnets/{{ mgmt_subnet_name }}"
            public_ip_address:
              id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/publicIPAddresses/{{ bastion_vm_name }}-PIP"
            private_ip_allocation_method: Dynamic
