---
- name: Deployment playbook initialization
  hosts: localhost
  connection: local
  tasks:

  - name: Create resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: "dev_123_pedro"
      location: "eastus"

  - name: Create storage account
    azure.azcollection.azure_rm_storageaccount:
      resource_group: "dev_123_pedro"
      name: pedro123pedro
      account_type: Standard_LRS

  - name: Successful Object creation
    ansible.builtin.set_fact:
      exec_rc: 0
      exec_message: “Azure RG and Storage account created with success”
