---
- name: Create Azure VMs and NICs then configure NICs for Load Balance
  hosts: localhost
  connection: local
  tasks:

  - name: Set some facts
    ansible.builtin.set_fact:
      vm_count: 0

  - name: Create and configure NICs for VMs
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "vm{{ item }}-nic"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ backend_subnet_name }}"
      security_group: "{{ backend_nsg_name }}"
      ip_configurations:
        - name: "ipconfig{{ item }}"
          primary: yes
          load_balancer_backend_address_pools:
            - name: "backend-pool"
              loadbalancer: "{{ lb_name }}"
    loop: "{{ range(1, vm_count + 1)|list }}"
    register: nics

  - name: Set some facts
    ansible.builtin.set_fact:
      vm_count: 0

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "web-vm{{ item }}"
      location: "{{ location }}"
      vm_size: "{{ vm_size }}"
      managed_disk_type: "{{ storage_account_type }}"
      os_disk_size_gb: "{{ disk_size }}"
      storage_account: "{{ storage_account }}"
      storage_container: vm{{ item }}container
      storage_blob: vm{{ item }}blob.vhd
      admin_username: {{ admin_username }}
      admin_password: {{ admin_password }}
      network_interfaces: "vm{{ item }}-nic"
      image:
        offer: ubuntu-24_04-lts
        publisher: Canonical
        sku: 'ubuntu-pro'
        version: latest
    loop: "{{ range(1, vm_count + 1)|list }}"
 
  - name: Successful Object creation
    ansible.builtin.set_fact:
      exec_rc: 0
      exec_message: “Azure VMs and NICs were created and configured with success”
