---
- name: Login to PSE server
  delegate_to: "{{ jump_host }}"
  block:
    - name: Check the activity of systemctl
      connection_zscaler:
        host: "{{ hostname }}"
        username: "{{ zscaler_user }}"
        password: "{{ zscaler_passwd }}"
        device_type: "linux"
        commands:
          - "systemctl status zpa-service-edge"
      register: status_command_output

    - name: Transfer the ticket if the systemctl status is not running
      when: "'active (running)' not in status_command_output.stdout"
      ansible.builtin.set_fact:
        exec_success: true
        exec_changed: false
        exec_rc: 2
        exec_message: “Systemctl status is not active”

    - name: If the activity status is active, stop the service and reboot it
      when: "'active (running)' in status_command_output.stdout"
      block:
        - name: Reboot the service and again check the status
          connection_zscaler:
            host: "{{ hostname }}"
            username: "{{ zscaler_user }}"
            password: "{{ zscaler_passwd }}"
            device_type: "linux"
            commands:
              - "sudo systemctl stop zpa-service-edge"
              - "sudo reboot"
          register: reboot

        - name: Wait for sometime
          ansible.builtin.pause:
            seconds: 100

        - name: Reboot the service and again check the status
          connection_zscaler:
            host: "{{ hostname }}"
            username: "{{ zscaler_user }}"
            password: "{{ zscaler_passwd }}"
            device_type: "linux"
            commands:
              - "sudo systemctl start zpa-service-edge"
          register: restart

        - name: Wait for service to start
          ansible.builtin.pause:
            seconds: 300

        - name: Check the activity of systemctl
          connection_zscaler:
            host: "{{ hostname }}"
            username: "{{ zscaler_user }}"
            password: "{{ zscaler_passwd }}"
            device_type: "linux"
            commands:
              - "systemctl status zpa-service-edge"
          register: status_command_output_new

        - name: Transfer the ticket if the status is not up
          when: "'active (running)' not in status_command_output_new.stdout"
          ansible.builtin.set_fact:
            exec_success: true
            exec_changed: false
            exec_rc: 2
            exec_message: “Systemctl status is not up after rebooting or might taking so long to come up, please check manually”

        - name: Now check the swap file level again
          ansible.builtin.include_tasks: connect_zscaler.yml
          when: "'active (running)' in status_command_output_new.stdout"

      rescue:
        - name: Service status is not active
          ansible.builtin.set_fact:
            exec_success: true
            exec_changed: false
            exec_rc: 2
            exec_message: “There is some issues while rebooting or again connecting to PSE server”

  rescue:
    - name: Login to Server is not successful
      ansible.builtin.set_fact:
        exec_success: true
        exec_changed: false
        exec_rc: 2
        exec_message: “There is some issues while connecting to server or commands on server might fail, please check manually”
